config/routes.rb
EOPES::Application.routes.draw do
  resources :user_skills, :only => [:index,:create]

  get 'market_explorer/index'
  get 'market_explorer/market_groups'
  get 'market_explorer/set_location'
  get 'market_explorer/set_current_location'
  get 'market_explorer/get_market'

  resources :estimates do
    collection do
      get "select"
      post "select_new"
      get "set_location"
      get "set_material"
      get "set_result"
      get "set_sell_market_list"
    end

    member do
      get "set_location"
      get "set_material"
      get "set_result"
      get "set_sell_market_list"
    end
  end

  get 'crest_debugs', to:"crest_debugs#index"
  get 'crest_debugs/get_crest'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  get "home/index"
  get "welcome/index"

  root 'welcome#index'
  get "home", to: "home#index", as: "user_root"

end

app/models/estimate.rb
# == Schema Information
#
# Table name: estimates
#
#  id                  :integer          not null, primary key
#  type_id             :integer
#  user_id             :integer
#  sell_price          :decimal(20, 4)
#  sell_count          :integer
#  product_type_id     :integer
#  total_cost          :decimal(20, 4)
#  sell_total_price    :decimal(20, 4)
#  material_total_cost :decimal(20, 4)
#  profit              :decimal(20, 4)
#  total_volume        :decimal(20, 4)
#  created_at          :datetime
#  updated_at          :datetime
#

class Estimate < ActiveRecord::Base
  has_many :estimate_materials, :dependent => :destroy
  has_one :estimate_blueprint, :dependent => :destroy
  has_one :estimate_job_cost, :dependent => :destroy

  #Production Time算出
  #base * timeModifier * skillModifier * runs
  #timeModifier = TEModifier and Facility Modifier (1.0 for NPC Station, 0.75 for many Pos assembly)
  #skillModifier = Industry:4% Advanced Industry:3%
  def calc_production_time(type_id, te, runs, user_id, pos_flag = false)
    base_time = IndustryActivity.where(:typeID => type_id, :activityID => 1).first.time
    if pos_flag then
      time_modifier = (0.75 - (te * 0.01))
    else
      time_modifier = (1.0 - (te * 0.01))
    end
    skill_modifier = get_production_skill_modifier(user_id)
    production_time = base_time * time_modifier * skill_modifier * runs
    return production_time.ceil
  end

  def get_production_skill_modifier(user_id)
    #UserSkill取得し、存在しない場合はDefault値を設定する
    user_skills = UserSkill.where(:user_id => user_id)
    skill_3380 = 5 #Industry
    skill_3388 = 5 #Advanced Industry
    user_skills.each do |s|
      if s.skill_id == 3380
        skill_3380 = s.skill_level.to_i
      end
      if s.skill_id == 3388
        skill_3388 = s.skill_level.to_i
      end
    end

    skill_modifier = (1 - (0.04 * skill_3380)) * (1- (0.03 * skill_3388))
    return skill_modifier
  end

end

app/models/form/estimate_form.rb
class EstimateForm
  include ActiveModel::Model

  attr_accessor :estimate
  attr_accessor :estimate_blueprint
  attr_accessor :estimate_job_cost
  attr_accessor :user_id
  attr_accessor :jita_price

  def get_jita_price!(access_token)
    #材料一覧取得
    material_list = Array.new
    materials = IndustryActivityMaterial.where(:typeID => self.estimate_blueprint.type_id, :activityID => 1)
    jita_price = Hash::new()

    #マーケットデータリフレッシュ(The Forge)
    materials.each do |material|
      material_list << material.materialTypeID
    end
    Market.refresh_market_parallel(10000002, material_list, access_token)

    #Get The Forge Price
    materials.each do |material|
      #Jita Top 15 low Price
      market_details = MarketDetail
                           .includes(:market)
                           .where(station_id: 60003760, markets: {type_id: material.materialTypeID})
                           .order(:price)
                           .limit(15)

      #average
      average_price = 0
      sum = 0.0
      count = 0
      market_details.each do |v|
        sum += v.price
      end
      #Jita Market に存在しない場合は 原料価格は0 とする
      #存在する場合は 平均 を 原料価格とする
      if market_details.nil? || sum == 0.0
        v = 0
      else
        v = sum / market_details.size
      end
      jita_price.store(material.materialTypeID, v)
    end
    self.jita_price = jita_price
  end

  def get_material_list
    EstimateMaterial.get_material_list(self.estimate_blueprint.type_id,
                                       self.estimate_blueprint.me,
                                       self.estimate_blueprint.te,
                                       self.estimate_blueprint.runs,
                                       self.jita_price)
  end

  #Market Data 一覧取得
  #Price が 安いもののTop10 を取得する
  def get_market_data(access_token, region_id, type_id)
    #マーケットデータリフレッシュ
    Market.refresh_market(region_id, type_id, access_token)
    MarketDetail.get_market_data_order_by_price(type_id, region_id, 10)
  end

  #Total Estimate Result 再計算
  def set_total_price!(material_list)
    #sell total count
    product_quantity = IndustryActivityProduct.where(:typeID => self.estimate_blueprint.type_id, :activityID => 1).first
    self.estimate.sell_count = product_quantity.quantity * self.estimate_blueprint.runs

    #Total Volume
    self.estimate.total_volume = self.estimate.sell_count * InvType.get_type_volume(self.estimate.product_type_id)

    #Sell Total Price
    self.estimate.sell_total_price = self.estimate.sell_count * self.estimate.sell_price

    #material total cost
    self.estimate.material_total_cost = 0.0
    material_list.each do |m|
      self.estimate.material_total_cost += m.total_price
    end

    #Production Time
    self.estimate.production_time = self.estimate.calc_production_time(self.estimate_blueprint.type_id,
                                                                       self.estimate_blueprint.te,
                                                                       self.estimate_blueprint.runs,
                                                                       self.user_id)
    #Total Cost
    self.estimate.total_cost = self.estimate_job_cost.total_job_cost + self.estimate.material_total_cost

    #Profit
    self.estimate.profit = self.estimate.sell_total_price.to_f - self.estimate.total_cost.to_f
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @estimates = Estimate.where(:user_id => get_current_user_id)
    respond_with(@estimates)
  end

  def show
    #location
    @region_list = MapRegion.all.order(:regionName).map { |list| [list.regionName, list.regionID] }
    #market sell order
    #Default は The Forge
    @sell_region_id = 10000002
    @product_market_list = @estimate_form.get_market_data(get_token,
                                                          @sell_region_id,
                                                          @estimate_form.estimate.product_type_id)

    respond_with(@estimate)
  end

  def select
    @estimate = Estimate.new
    respond_with(@estimate)
  end

  def new
    @estimate_form = EstimateForm.new
    @estimate_form.user_id = get_current_user_id

    #blueprint
    @estimate_blueprint = EstimateBlueprint.new
    @estimate_blueprint.type_id = session[:type_id]
    @estimate_blueprint.runs = 1
    @estimate_blueprint.me = 10
    @estimate_blueprint.te = 20
    @estimate_form.estimate_blueprint = @estimate_blueprint

    #jita price
    @estimate_form.get_jita_price!(get_token)

    #material
    @material_list = @estimate_form.get_material_list

    #location
    @region_list = MapRegion.all.order(:regionName).map { |list| [list.regionName, list.regionID] }
    @solar_system_list = [["", ""]]

    #Job Cost 計算
    @estimate_job_cost = EstimateJobCost.new
    @estimate_job_cost.re_calc_job_cost!(@material_list,@estimate_blueprint.runs)
    @estimate_form.estimate_job_cost = @estimate_job_cost

    #Estimate
    @estimate_form.estimate = Estimate.new
    #Product Setting
    @estimate_form.estimate.product_type_id = @estimate_blueprint.get_product_type_id

    #market sell order
    #Default は The Forge
    @sell_region_id = 10000002
    @product_market_list = @estimate_form.get_market_data(get_token,
                                                          @sell_region_id,
                                                          @estimate_form.estimate.product_type_id)

    #Product Sell Order Average
    @product_region_sell_price_average =
        MarketDetail.get_region_average_price(@sell_region_id, @estimate_form.estimate.product_type_id)
    @product_universe_sell_price_average =
        MarketPrice.get_universe_average_price(@estimate_form.estimate.product_type_id)

    #Product Sell Price
    @estimate_form.estimate.sell_price = @product_region_sell_price_average

    #Total Estimate Result
    @estimate_form.set_total_price!(@material_list)
    #session
    session[:estimate_form] = @estimate_form
    session[:material_list] = @material_list
    respond_with(@estimate_form)
  end

  def select_new
    session[:type_id] = params[:estimate][:type_id]
    redirect_to new_estimate_path
  end

  def edit
    #jita price
    @estimate_form.get_jita_price!(get_token)

    #material
    @material_list = @estimate.estimate_materials

    #location 再設定
    @region_id = @estimate.estimate_job_cost.region_id
    @solar_system_id = @estimate.estimate_job_cost.solar_system_id

    #location
    @region_list = MapRegion.all.order(:regionName).map { |list| [list.regionName, list.regionID] }
    @solar_system_list = MapSolarSystem.where(:regionID => @region_id)
    .order(:solarSystemName)
    .map { |list| [list.solarSystemName, list.solarSystemID] }

    #Cost Re Calc
    @estimate_form.estimate_job_cost.re_calc_job_cost!(@material_list,@estimate.estimate_blueprint.runs)

    #market sell order
    #Default は The Forge
    @sell_region_id = 10000002
    @product_market_list = @estimate_form.get_market_data(get_token,
                                                          @sell_region_id,
                                                          @estimate_form.estimate.product_type_id)

    #Product Sell Order Average
    @product_region_sell_price_average =
        MarketDetail.get_region_average_price(@sell_region_id, @estimate_form.estimate.product_type_id)
    @product_universe_sell_price_average =
        MarketPrice.get_universe_average_price(@estimate_form.estimate.product_type_id)

    #Total Estimate Result
    @estimate_form.set_total_price!(@material_list)
    #session
    session[:estimate_form] = @estimate_form
    session[:material_list] = @material_list
  end

  def create
    #Get Session
    @material_list = session[:material_list]
    @estimate_form = session[:estimate_form]

    #見積基本情報を設定
    @estimate = @estimate_form.estimate
    @estimate.user_id = get_current_user_id

    #見積詳細情報(Material)を設定
    @material_list.each do |material|
      @estimate.estimate_materials << material
    end

    #見積詳細情報(Blueprint)を設定
    @estimate.estimate_blueprint = @estimate_form.estimate_blueprint

    #見積詳細情報(JobCost)を設定
    @estimate.estimate_job_cost = @estimate_form.estimate_job_cost

    @estimate.save
    respond_with(@estimate)
  end

  def update
    #Get Session
    @material_list = session[:material_list]
    @estimate_form = session[:estimate_form]

    #見積基本情報を設定
    @estimate = @estimate_form.estimate
    @estimate.user_id = get_current_user_id

    #見積詳細情報(Material)を設定
    @material_list.each do |material|
      @estimate.estimate_materials << material
    end

    #見積詳細情報(Blueprint)を設定
    @estimate.estimate_blueprint = @estimate_form.estimate_blueprint

    #見積詳細情報(JobCost)を設定
    @estimate.estimate_job_cost = @estimate_form.estimate_job_cost

    @estimate.save
    respond_with(@estimate)
  end

  def destroy
    @estimate.destroy
    respond_with(@estimate)
  end

  def set_location
    @estimate_form = session[:estimate_form]
    @material_list = session[:material_list]

    # select value setting
    @region_id = params[:region_id]
    @solar_system_id = params[:solar_system_id]

    #region_list and solar_system_list
    @region_list = MapRegion.all.order(:regionName).map { |list| [list.regionName, list.regionID] }
    @solar_system_list = MapSolarSystem.where(:regionID => @region_id)
    .order(:solarSystemName)
    .map { |list| [list.solarSystemName, list.solarSystemID] }

    #Re Set Location
    @estimate_form.estimate_job_cost.region_id = @region_id
    @estimate_form.estimate_job_cost.solar_system_id = @solar_system_id

    #Cost Re Calc
    @estimate_form.estimate_job_cost.re_calc_job_cost!(@material_list,@estimate_form.estimate_blueprint.runs)

    #session ReEntry
    session[:estimate_form] = @estimate_form
  end

  def set_material
    #material
    @material_list = session[:material_list]
    @estimate_form = session[:estimate_form]
    @estimate_form.estimate_blueprint.me = params["me"].to_i
    @estimate_form.estimate_blueprint.te = params["te"].to_i
    @estimate_form.estimate_blueprint.runs = params["runs"].to_i
    @material_list.each_with_index do |m, i|
      #Re Calc Require Material
      @material_list[i].require_count = EstimateMaterial.require_material(@estimate_form.estimate_blueprint.runs,
                                                                          @material_list[i].base_quantity,
                                                                          @estimate_form.estimate_blueprint.me,
                                                                          false)
      @material_list[i].price = params["price_" + i.to_s]
      @material_list[i].total_price = params["price_" + i.to_s].to_f * @material_list[i].require_count.to_f
      @material_list[i].total_volume = @material_list[i].require_count * @material_list[i].volume
    end

    #session ReEntry
    session[:material_list] = @material_list
    session[:estimate_form] = @estimate_form
  end

  def set_result
    #Get Session
    @material_list = session[:material_list]
    @estimate_form = session[:estimate_form]
    @estimate_form.estimate.sell_price = params["sell_price"].to_f

    #Calc Total Price
    @estimate_form.set_total_price!(@material_list)

    #session ReEntry
    session[:material_list] = @material_list
    session[:estimate_form] = @estimate_form
  end

  #Sell Market List
  def set_sell_market_list
    #Get Session
    @estimate_form = session[:estimate_form]

    # select value setting
    @sell_region_id = params[:sell_region_id]

    #region_list
    @region_list = MapRegion.all.order(:regionName).map { |list| [list.regionName, list.regionID] }

    #market sell order
    @product_market_list = @estimate_form.get_market_data(get_token, @sell_region_id, @estimate_form.estimate.product_type_id)

    #Product Sell Order Average
    @product_region_sell_price_average =
        MarketDetail.get_region_average_price(@sell_region_id, @estimate_form.estimate.product_type_id)
    @product_universe_sell_price_average =
        MarketPrice.get_universe_average_price(@estimate_form.estimate.product_type_id)
  end

  private
  def set_estimate
    @estimate = Estimate.find(params[:id])
    #ページ認可
    page_permission(@estimate.user_id)

    @estimate_form = EstimateForm.new
    @estimate_form.user_id = get_current_user_id
    @estimate_form.estimate = @estimate
    @estimate_form.estimate_blueprint = @estimate.estimate_blueprint
    @estimate_form.estimate_job_cost = @estimate.estimate_job_cost

  end

  def estimate_params
    params.require(:estimate).permit(:type_id, :user_id)
  end

  #ページ認可
  def page_permission(user_id)
    if user_id.to_s != get_current_user_id.to_s
      redirect_to home_index_path
    end
  end

end

app/helpers/estimates_helper.rb
module EstimatesHelper
  def get_region_name(region_id)
    region = MapRegion.where(:regionID => region_id).first
    if region.nil?
      "All Region"
    else
      region.regionName
    end
  end

  def get_solar_system_name(solar_system_id)
    solar_system = MapSolarSystem.where(:solarSystemID => solar_system_id).first
    if solar_system.nil?
      "All Solar System"
    else
      solar_system.solarSystemName
    end
  end
end

app/views/estimates/_estimate_result.erb
<div class="box-body">
  <form role="form">
    <div class="form-group">
      <label>Sell Price</label>
      <%= text_field :estimate, :sell_price, class: 'form-control', value: @estimate_form.estimate.sell_price %>
    </div>
    <div class="box-body no-padding">
      <table class="table table-condensed">
        <tr>
          <th style="width: 40px">#</th>
          <th>Product</th>
          <th>Quantity</th>
          <th>Volume</th>
        </tr>
        <tr>
          <td>
            <%= image_tag("https://image.eveonline.com/Type/#{@estimate_form.estimate.product_type_id}_32.png",
                          :alt => "Type Image") %>
          </td>
          <td>
            <%= InvType.get_type_name(@estimate_form.estimate.product_type_id) %>
          </td>
          <td>
            <%= @estimate_form.estimate.sell_count %>
          </td>
          <td>
            <%= @estimate_form.estimate.total_volume %>
          </td>
        </tr>
      </table>
    </div>
    <br/>

    <div class="box-body no-padding">
      <table class="table table-condensed">
        <tr>
          <th style="width: 20%">Result</th>
          <th style="width: 30%"></th>
          <th style="width: 30%"></th>
          <th style="width: 20%"></th>
        </tr>
        <tr>
          <td>
            Sell Price Total
          </td>
          <td></td>
          <td>
            <%= number_to_currency(@estimate_form.estimate.sell_total_price,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Costs
          </td>
          <td></td>
          <td>
            <%= number_to_currency(@estimate_form.estimate.total_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
          </td>
          <td>
            Job Install Cost
          </td>
          <td>
          </td>
          <td>
            <%= number_to_currency(@estimate_form.estimate_job_cost.total_job_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
        </tr>
        <tr>
          <td>
          </td>
          <td>
            Material Total Cost
          </td>
          <td>
          </td>
          <td>
            <%= number_to_currency(@estimate_form.estimate.material_total_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
        </tr>
        <tr>
          <td>
            Profit
          </td>
          <td></td>
          <td>
            <%= number_to_currency(@estimate_form.estimate.profit,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Production Time
          </td>
          <td></td>
          <td>
            <%= second_to_time(@estimate_form.estimate.production_time) %>
          </td>
          <td></td>
        </tr>
      </table>
    </div>
  </form>
</div>
<script>
    $('#estimate_sell_price').change(function () {
        set_result();
    });
</script>

app/views/estimates/_form.html.erb
<%= form_for @estimate_form, url: estimates_path, method: :post do |f| %>
    <section class="content">
      <% if @estimate_form.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@estimate_form.errors.count, "error") %> prohibited this estimate from being saved:</h2>

            <ul>
              <% @estimate_form.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class='col-md-12'>

        <!-- Blueprint Start-->
        <%= f.fields_for :estimate_blueprints, @estimate_form.estimate_blueprint do |blueprint_field| %>
            <div class='col-md-6'>
              <div class="box box-warning">
                <div class="box-header">
                  <h3 class="box-title">Blueprint</h3>
                </div>
                <div class="box-body">
                  <form role="form">
                    <%= image_tag("https://image.eveonline.com/Type/#{@estimate_form.estimate_blueprint.type_id}_32.png",
                                  :alt => "Type Image") %>
                    <%= InvType.get_type_name(@estimate_form.estimate_blueprint.type_id) %>
                    <br/>
                    <br/>

                    <div class="form-group">
                      <label>Select Blueprint</label>
                      <select class="form-control">
                        <option>Not Use This Version</option>
                      </select>
                    </div>
                    <div class='col-md-6'>
                      <div class="form-group">
                        <%= blueprint_field.label :me, "ME" %>
                        <br>
                        <%= blueprint_field.number_field :me, class: 'form-control' %>
                      </div>
                    </div>
                    <div class='col-md-6'>
                      <div class="form-group">
                        <%= blueprint_field.label :te, "TE" %>
                        <br>
                        <%= blueprint_field.number_field :te, class: 'form-control' %>
                      </div>
                    </div>
                    <div class="form-group">
                      <%= blueprint_field.label :runs %>
                      <br>
                      <%= blueprint_field.number_field :runs, class: 'form-control' %>
                    </div>
                  </form>
                </div>
              </div>
            </div>
        <% end %>
        <!-- Blueprint End-->

        <!-- Skill Start-->
        <div class='col-md-6'>
          <div class="box box-warning">
            <div class="box-header">
              <h3 class="box-title">Location</h3>
            </div>
            <div id="location">
              <%= render :partial => 'location' %>
            </div>
          </div>
        </div>
        <!-- Skill End-->
      </div>

      <div class='col-md-12'>
        <!-- Material Start-->
        <div class='col-md-12'>
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Material</h3>
            </div>
            <div id="material">
              <%= render :partial => 'material' %>
            </div>
          </div>
          <!-- /.box -->
        </div>
        <!-- Material End-->
      </div>
      <div class='col-md-12'>
        <!-- Estimate Result Start-->
        <div class='col-md-12'>
          <div class="box box-warning">
            <div class="box-header">
              <h3 class="box-title">Estimate Result</h3>
            </div>
            <div class="row">
              <div class='col-md-6'>
                <div id="estimate_result">
                  <%= render :partial => 'estimate_result' %>
                </div>
              </div>
              <div class='col-md-6'>
                <div id="sell_order">
                  <%= render :partial => 'sell_order' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Product End-->
      </div>
      <%= f.submit button_value, :class => 'btn btn-primary' %>
    </section>
<% end %>

<script>
    $('#estimate_form_estimate_blueprints_me').change(function () {
        set_material(<%=@material_list.count()%>);
    });
    $('#estimate_form_estimate_blueprints_te').change(function () {
        set_material(<%=@material_list.count()%>);
    });
    $('#estimate_form_estimate_blueprints_runs').change(function () {
        set_material(<%=@material_list.count()%>);
    });
    $('#commit').click(function () {
        $('#estimate_form').submit();
    })
</script>

app/views/estimates/_location.erb
<div class="box-body">
  <form role="form">
    <div class="form-group">
      <label>Select</label>
      <%= select_tag :region_id, options_for_select(@region_list,@region_id), :prompt => "All Region", class: 'form-control' %>
    </div>
    <div class="form-group">
      <label>Select</label>
      <%= select_tag :solar_system_id, options_for_select(@solar_system_list,@solar_system_id), :prompt => "All Solar System", class: 'form-control' %>
    </div>
    <div class="form-group">
      <label>System Cost Index</label> :
      <%= @estimate_form.estimate_job_cost.system_cost_index %>
      <div class="progress sm progress-striped active">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
             aria-valuemin="0" aria-valuemax="100" style="width: <%= @estimate_form.estimate_job_cost.system_cost_index * 100%>%">
          <span class="sr-only">20% Complete</span>
        </div>
      </div>
    </div>
    <div class="box-body no-padding">
      <table class="table table-condensed">
        <tr>
          <th>Base Job Cost</th>
          <th>Job Fee</th>
          <th>Facility Cost</th>
          <th>Job Install Cost</th>
        </tr>
        <tr>
          <td>
            <%= number_to_currency(@estimate_form.estimate_job_cost.base_job_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td>
            <%= number_to_currency(@estimate_form.estimate_job_cost.job_fee,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td>
            <%= number_to_currency(@estimate_form.estimate_job_cost.facility_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
          <td>
            <%= number_to_currency(@estimate_form.estimate_job_cost.total_job_cost,
                                   :precision => 2,
                                   :unit => "isk",
                                   :separator => ".",
                                   :format => "%n %u") %>
          </td>
        </tr>
      </table>
    </div>
  </form>
</div>

<script>
    $('#region_id').change(function () {
        set_location_change_region();
    });
    $('#solar_system_id').change(function () {
        set_location_change_solar_system();
    });
</script>

app/views/estimates/edit.html.erb
<section class="content-header">
  <h1>Estimate Product</h1>
</section>

<%= render :partial => 'form', :locals => {:button_value => 'Update Estimate'} %>

<%= link_to 'Back', :back %>

app/views/estimates/index.html.erb
<section class="content-header">
  <h1>Listing estimates</h1>
</section>

<section class="content">
  <div class="row">
    <div class="box">
      <div class="box-body">
        <table id="lists" class="table table-bordered table-striped" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th style="width: 40px">#</th>
            <th>Product</th>
            <th>Total Cost</th>
            <th>Total Sell Price</th>
            <th>Profit</th>
            <th>Count</th>
            <th>Total Volume</th>
            <th>Created</th>
            <th>Updated</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @estimates.each do |estimate| %>
              <tr>
                <td><%= image_tag("https://image.eveonline.com/Type/#{estimate.product_type_id}_32.png",
                                  :alt => "Type Image") %> </td>
                <td><%= InvType.get_type_name(estimate.product_type_id) %></td>
                <td><%= number_to_currency(estimate.total_cost,
                                           :precision => 2,
                                           :unit => "isk",
                                           :separator => ".",
                                           :format => "%n %u") %>
                </td>
                <td><%= number_to_currency(estimate.sell_total_price,
                                           :precision => 2,
                                           :unit => "isk",
                                           :separator => ".",
                                           :format => "%n %u") %>
                </td>
                <td><%= number_to_currency(estimate.profit,
                                           :precision => 2,
                                           :unit => "isk",
                                           :separator => ".",
                                           :format => "%n %u") %>
                </td>
                <td><%= estimate.sell_count %></td>
                <td><%= estimate.total_volume %></td>
                <td><%= estimate.created_at %></td>
                <td><%= estimate.updated_at %></td>
                <td><%= link_to 'Show', estimate %></td>
                <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
                <td><%= link_to 'Destroy', estimate, method: :delete, data: {confirm: 'Are you sure?'} %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>

  <%= link_to 'New Estimate', select_estimates_path %>
</section>

app/views/estimates/new.html.erb
<section class="content-header">
  <h1>Estimate Product</h1>
</section>

<%= render :partial => 'form', :locals => {:button_value => 'Create Estimate'} %>

<%= link_to 'Back', :back %>

app/views/estimates/select.erb
<section class="content-header">
  <h1>Select Estimate Item</h1>
</section>

<section class="content">
  <%= form_for @estimate, url: select_new_estimates_path, method: :post do |f| %>
      <% if @estimate.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

            <ul>
              <% @estimate.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <label>Select Blueprint</label>
        <%= f.collection_select :type_id, IndustryActivity.get_industry, :typeID, :typeName, {pronpt: ""}, class: 'form-control' %>
      </div>
      <div>
        <%= f.submit 'Select', :class => 'btn btn-primary' %>
      </div>
      <br/>
      <%= link_to 'Back', estimates_path %>
  <% end %>
</section>