config/routes.rb
EOPES::Application.routes.draw do
  resources :user_skills, :only => [:index,:create]

  get 'market_explorer/index'
  get 'market_explorer/market_groups'
  get 'market_explorer/set_location'
  get 'market_explorer/set_current_location'
  get 'market_explorer/get_market'

  resources :estimates do
    collection do
      get "select"
      post "select_new"
      get "set_location"
      get "set_material"
      get "set_result"
      get "set_sell_market_list"
    end

    member do
      get "set_location"
      get "set_material"
      get "set_result"
      get "set_sell_market_list"
    end
  end

  get 'crest_debugs', to:"crest_debugs#index"
  get 'crest_debugs/get_crest'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  get "home/index"
  get "welcome/index"

  root 'welcome#index'
  get "home", to: "home#index", as: "user_root"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>EOPES</title>
  <%= include_gon %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>

<% if user_signed_in? %>
    <body class="skin-black">
    <header class="header">
      <a href="#" class="logo">
        <%= image_tag("EOPES_Logo.png", :size => "210x48") %>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
      </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="left-side sidebar-offcanvas">
        <section class="sidebar">
          <div class="user-panel">
            <div class="pull-left image">
              <%= image_tag("https://image.eveonline.com/Character/#{session[:user_id]}_32.jpg", :class => "img-circle", :alt => "User Image") %>
            </div>
            <div class="pull-left info">
              <p> <%= session[:user_name] %></p>
            </div>
          </div>
          <ul class="sidebar-menu">
            <li class="<%= active?("home") %>">
              <%= link_to home_index_path do %>
                  <%= image_tag("info.png", :size => "48x48") %>
                  <span>Home</span>
              <% end %>
            </li>
            <li class="<%= active?("estimates") %>">
              <%= link_to estimates_path do %>
                  <%= image_tag("calculator.png", :size => "48x48") %>
                  <span>Industry Profit Calc</span>
              <% end %>
            </li>
            <li class="<%= active_market_explorer?("market_explorer", "Sell") %>">
              <%= link_to market_explorer_index_path(:market_kind => "Sell") do %>
                  <%= image_tag("market.png", :size => "48x48") %>
                  <span>Market Explorer(Sell)</span>
              <% end %>
            </li>
            <li class="<%= active_market_explorer?("market_explorer", "Buy") %>">
              <%= link_to market_explorer_index_path(:market_kind => "Buy") do %>
                  <%= image_tag("market.png", :size => "48x48") %>
                  <span>Market Explorer(Buy)</span>
              <% end %>
            </li>
            <li class="<%= active?("user_skills") %>">
              <%= link_to user_skills_path do %>
                  <%= image_tag("levelTrained.png", :size => "48x48") %>
                  <span>User Skill</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= image_tag("memberdelay.png", :size => "48x48") %>
                  <span>Logout</span>
              <% end %>
            </li>
          </ul>
        </section>
      </aside>

      <!-- Right side column. Contains the navbar and content of the page -->
      <aside class="right-side">
        <%= yield %>
      </aside>
      <!-- /.right-side -->
    </div>
    <!-- ./wrapper -->
    </body>
<% else %>
    <%= yield %>
<% end %>
</html>